<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ApiCategoriaControllerTest extends TestCase
{
    /**
     * @var string
     */
    protected $base_api_url;

    protected function setUp(): void
    {
        $this->base_api_url = env("APP_URL", "http://localhost") . "/api";
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     *
     * @return void
     */ 
    public function test()
    {

        $response = $this->get($this->base_api_url . '/categorias');

        $response->assertStatus(200);
    }
}
